name: PHP Composer

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      
      - name: Change to PHP 7.1
        run: sudo update-alternatives --set php /usr/bin/php7.1
      
      - name: Install Pandoc
        run: sudo apt-get install pandoc

      - name: Install Composer and Dependencies
        run: curl -s http://getcomposer.org/installer | php && php composer.phar self-update && php composer.phar install

      - name: Full Analysis with Coverage
        run: php composer.phar check-full
